version: '3.8'

services:
  # Микросервис User.Service
  user-service:
    build:
      context: ./User.Service
      dockerfile: User.Service.Presentation/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=host=db;Port=5432;Database=userdb;User ID=postgres;Password=root;
    depends_on:
      - pgadmin
      - redis
      - logstash
      - kibana
      - rabbitmq

  # Микросервис Stream.Service
  stream-service:
    build:
      context: ./Stream.Service
      dockerfile: Stream.Service.Presentation/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=StreamDb
    depends_on:
      - mongodb
      - logstash
      - kibana
      - rabbitmq

  # Микросервис Notification.Service
  notification-service:
    build:
      context: ./Notification.Service
      dockerfile: Notification.Service.Presentation/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisSettings__ConnectionString=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  elasticsearch:
    image: bitnami/elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: bitnami/logstash:8.9.2
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"

  kibana:
    image: bitnami/kibana:8.9.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  postgres_data:
  esdata:
  mongo-data: